default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= 5 %>
development:
  <<: *default
  database: <%= ENV["DATABASE_NAME_DEVELOPMENT"] %>
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  host: <%= ENV["DATABASE_HOST"] %>
test:
  <<: *default
  database: <%= ENV["DATABASE_NAME_TEST"] %>
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  host: <%= ENV["DATABASE_HOST"] %>
production:
  url:  <%= ENV["DATABASE_URL"] %>
